config:
  credentials: []
  project_repos:
    code-repo.d4science.org/MaDgIK/eosc-explore:
      branch: master
      repo: https://code-repo.d4science.org/MaDgIK/eosc-explore
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      code-repo.d4science.org/MaDgIK/eosc-explore git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-ivory-owl.sh
        container: qc.acc_silly-linen-buffalo
  QC.Doc:
    repos:
      code-repo.d4science.org/MaDgIK/eosc-explore find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-russet-tiger.sh
        container: qc.doc_bluesy-olive-maltese
      code-repo.d4science.org/MaDgIK/eosc-explore git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-chestnut-grasshopper.sh
        container: qc.doc_jumpy-orchid-foxhound
      code-repo.d4science.org/MaDgIK/eosc-explore markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-fuchsia-tortoise.sh
        container: qc.doc_pasty-chocolate-loon
  QC.Lic:
    repos:
      code-repo.d4science.org/MaDgIK/eosc-explore licensee:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-dandelion-jackal.sh
        container: qc.lic_surly-myrtle-civet
  QC.Sty:
    repos:
      code-repo.d4science.org/MaDgIK/eosc-explore jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-lavender-impala.sh
        container: qc.sty_breezy-emerald-salamander
  QC.Ver:
    repos:
      code-repo.d4science.org/MaDgIK/eosc-explore get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-auburn-russel.sh
        container: qc.ver_crabby-cinnamon-crane
timeout: 1800
